export type EnglishProduct = {
  slug: string;
  name: string;
  family: string;
  category: "Siwood Materials" | "Spatial Applications" | "Outdoor Furniture" | "Circular Logistics";
  short: string;
  description: string;
  image: string;
  material: string;
  features: string[];
  use: string;
};

export const categories = ["All Products", "Siwood Materials", "Spatial Applications", "Outdoor Furniture", "Circular Logistics"] as const;

export const products: EnglishProduct[] = [
  {slug:"smoof-basic",name:"SMOOF BASIC",family:"Yuan Siwood",category:"Siwood Materials",short:"A foundational WPC range with boards, profiles and multiple surface options.",description:"A foundational series developed from WPC wood–plastic composite. Its catalog includes flat boards, tongue-and-groove boards and structural profiles, with colour and surface options for outdoor flooring, fences and landscape components.",image:"/catalog/smoof-basic.jpg",material:"WPC wood–plastic composite",features:["Multiple profiles and dimensions","For weather-exposed applications","Colour and surface options","Machinable to project requirements"],use:"Decking, fences, railings and outdoor landscape components"},
  {slug:"smoof-raise",name:"SMOOF RAISE",family:"Jing Siwood",category:"Siwood Materials",short:"PVC boards and profiles for interiors, cabinetry and finishing systems.",description:"A PVC-based board and profile family. The catalog includes skirting, edging, panels and shaped sections that can be integrated into interior fit-outs, cabinetry and functional spaces.",image:"/catalog/smoof-raise.jpg",material:"PVC composite",features:["Boards and shaped profiles","Multiple colour options","Easy cleaning and maintenance","Suitable for integrated interior systems"],use:"Interior fit-outs, cabinetry, skirting and edge systems"},
  {slug:"smoof-free",name:"SMOOF FREE",family:"Ai Siwood",category:"Siwood Materials",short:"An HDPE series for boards, building interiors and weather-exposed components.",description:"An HDPE-based recycled composite series developed around water resistance, weather resistance and material stability. Cataloged boards and structural sections can be designed and machined for each site.",image:"/catalog/smoof-free.jpg",material:"HDPE composite",features:["Water and weather resistance","Multiple profile options","Supports recycled-material applications","Dimensions confirmed by project"],use:"Building interiors, outdoor panels and components for damp environments"},
  {slug:"smoof-happy",name:"SMOOF HAPPY",family:"Le Siwood",category:"Siwood Materials",short:"A HIPS series with colour and forming flexibility for spatial and creative applications.",description:"The HIPS series offers colour and forming flexibility. Cataloged items include screens, edging, treads and functional profiles for spaces requiring a strong visual identity or custom form.",image:"/catalog/smoof-happy.jpg",material:"HIPS composite",features:["Broad colour expression","Varied profile geometry","Suitable for design machining","Supports creative spatial applications"],use:"Screens, edging, treads, displays and custom components"},
  {slug:"smoof-grand",name:"SMOOF GRAND",family:"Sen Siwood",category:"Siwood Materials",short:"A flexible TPE series for resilient, slip-resistant or cushioning applications.",description:"A TPE-based flexible composite family that retains resilient and tactile qualities. It can be developed for slip resistance, covering and cushioning; actual hardness and specifications are confirmed for each application.",image:"/catalog/smoof-grand.jpg",material:"TPE flexible composite",features:["Flexibility and cushioning","Adjustable feel and colour","Custom profile capability","Functional formulations can be co-developed"],use:"Slip-resistant parts, coverings, cushioning and functional materials"},
  {slug:"architecture",name:"Architecture & Landscape Systems",family:"ARCHITECTURE",category:"Spatial Applications",short:"Integrated platforms, pavilions, cabins, fences and public landscape applications.",description:"Siwood materials extend to platforms, walkways, pavilions, fences, cabins and public spaces. Modular components combine weather resistance and maintainability while reducing reliance on natural timber.",image:"/catalog/architecture.jpg",material:"Siwood family selected for the site",features:["Outdoor weather resistance","Modular planning","Reduced use of natural timber","For public and private spaces"],use:"Parks, walkways, pavilions, fences and cabins"},
  {slug:"interior-system",name:"Interior Functional Spaces",family:"INTERIOR SYSTEM",category:"Spatial Applications",short:"Circular materials applied to kitchens, bathrooms, flooring and cabinetry.",description:"The catalog shows Siwood applications in kitchens, bathrooms, floors and cabinetry. Materials are selected for moisture, cleaning and surface-finish requirements, bringing circular materials beyond industrial settings.",image:"/catalog/interior.jpg",material:"PVC, HDPE and composite boards",features:["Water resistant and easy to clean","Integrated boards and cabinetry","Selectable surface colours","Made to spatial dimensions"],use:"Kitchens, bathrooms, cabinetry and interior flooring"},
  {slug:"lounge",name:"Lounge Seating",family:"LOUNGE SEATING",category:"Outdoor Furniture",short:"Bubble, Couch Potato and other seating for relaxed outdoor settings.",description:"The outdoor furniture range includes hanging chairs, lounge chairs, sofas and reclined seating. Woven textures and organic forms suit gardens, terraces, hotels and commercial leisure spaces.",image:"/catalog/lounge.jpg",material:"Outdoor woven material and metal structures",features:["Designed for outdoor settings","Multiple chairs and sofas","Individual or grouped layouts","Styles subject to catalog and availability"],use:"Gardens, terraces, hotels, pools and commercial leisure areas"},
  {slug:"sun-lounge",name:"Sun Lounges",family:"SUN LOUNGES",category:"Outdoor Furniture",short:"Recliners, canopies and beach furniture designed for extended outdoor use.",description:"From Beach and Rainbow to Sun Lounges, the catalog presents recliners, canopies and setting furniture that can be combined for poolsides, beaches and resort environments.",image:"/catalog/sun-lounge.jpg",material:"Weather-resistant outdoor surfaces and metal structures",features:["Reclining and canopy options","For coastal and pool settings","Coordinated spatial ranges","Colours and styles subject to availability"],use:"Poolsides, beaches, resorts and outdoor leisure spaces"},
  {slug:"dining",name:"Outdoor Dining Sets",family:"DINING SET",category:"Outdoor Furniture",short:"Dining tables, coffee tables and seating sets for outdoor gatherings of different sizes.",description:"The catalog includes round and long tables, coffee tables and varied seating, from compact arrangements to multi-person dining configurations for residential and commercial spaces.",image:"/catalog/dining.jpg",material:"Outdoor weave, panels and metal structures",features:["Sets for two or more people","Coordinated tables and chairs","Multiple design languages","Selected to suit the available space"],use:"Outdoor dining, garden gatherings, cafés and commercial spaces"},
  {slug:"recycled-pallet",name:"Recycled Pallet",family:"RECYCLED PALLET",category:"Circular Logistics",short:"A recyclable logistics pallet made with recycled PVC.",description:"The catalog presents an environmentally oriented pallet made with recycled PVC for warehousing, transport and export circulation. It does not rely on natural timber and can be recycled again after use.",image:"/catalog/pallet.jpg",material:"Recycled PVC",features:["Water resistant and easy to clean","No timber pest concern","Recyclable after use","Dimensions and loading confirmed by requirement"],use:"Warehousing, export transport and internal factory circulation"},
];

export function getProduct(slug: string) { return products.find((product) => product.slug === slug); }
