export const videos = [
  {slug:"landfill-recovery",title:"Landfill Excavation, Remediation and Production Process",category:"Environmental Governance",description:"A field record connecting landfill excavation and remediation with downstream production. It provides on-site context for understanding how waste governance and resource recovery may connect.",products:[] as string[]},
  {slug:"material-machining",title:"Siwood Can Be Machined Like Timber",category:"Material Processing",description:"A machining record showing how Siwood can enter familiar woodworking and manufacturing processes. The title describes the film topic; it does not mean every machining condition or mechanical property is identical to natural timber.",products:["architecture","interior-system"]},
  {slug:"siwood-natural-grain",title:"Naturally Formed Wood-Grain Fibres During Siwood Production",category:"Material Processing",description:"A record of the fibrous, wood-grain surface that forms during Siwood production. Actual pattern and texture may vary with formulation and process conditions.",products:["smoof-basic","smoof-free","smoof-happy","smoof-grand","architecture"]},
  {slug:"siwood-profiles",title:"Waste Plastic Made into Siwood Profiles",category:"Material Processing",description:"A manufacturing record showing waste plastic becoming usable profile stock for further assembly and machining in landscape, spatial and component applications.",products:["architecture"]},
  {slug:"siwood-profiles-2",title:"Waste Plastic Made into Siwood Profiles — Part 2",category:"Material Processing",description:"A second field record of Siwood profile production. Profile, dimension and application suitability must still be confirmed against product specifications.",products:["architecture"]},
  {slug:"recycled-pallet",title:"Waste Plastic Made into Pallets",category:"Product Applications",description:"A record of recycled plastic being applied to a logistics carrier. Loading capacity and dimensions must be confirmed against the actual product specification.",products:["recycled-pallet"]},
  {slug:"fire-resistant-board-test",title:"1,000°C Test of Fire-Resistant Plastic Board",category:"Material Testing",description:"The provider's original title is retained in translation. The stated temperature is a description of the film, not third-party certification, a fire rating or a building-use guarantee. Formal selection must rely on the relevant test report.",products:[] as string[]},
  {slug:"automated-production",title:"In-House Automated Gas-Spring Production Line",category:"Manufacturing Capability",description:"An introduction to an internally developed automated gas-spring production line, presented separately from the mixed-plastic resource-recovery process.",products:[] as string[]},
];

export const videoCategories = ["Environmental Governance","Material Processing","Product Applications","Material Testing","Manufacturing Capability"];
