import type { Metadata } from "next";
import Link from "next/link";
import PrintButton from "../../../governance/intake/PrintButton";
import SiteHeader from "../../../components/SiteHeader";
import { createPageMetadata } from "../../../lib/site";

export const metadata: Metadata = createPageMetadata({title:"Site Review Worksheet | GTC Waste Governance",description:"A worksheet for governments, cities and public utilities to organise waste sources, site conditions, monitoring records and governance objectives for an initial GTC technical review.",path:"/en/governance/intake",alternatePath:"/governance/intake",locale:"en_US"});

const Field = ({label,wide=false}:{label:string;wide?:boolean}) => <label className={wide?"intake-field intake-field-wide":"intake-field"}><span>{label}</span><input type="text" autoComplete="off"/></label>;
const Check = ({children}:{children:React.ReactNode}) => <label className="intake-check"><input type="checkbox"/> <span>{children}</span></label>;

export default function GovernanceIntakePage(){return <main className="intake-page">
  <SiteHeader locale="en" ctaLabel="Call to confirm transfer" ctaShortLabel="Call GTC" ctaHref="tel:+88665811589" />
  <section className="intake-hero"><div><p className="eyebrow">SITE REVIEW WORKSHEET / 01</p><h1>Site review worksheet</h1></div><div><p>This form helps governments, cities and public utilities organise information for a first technical discussion. Enter “To be confirmed” where information is not yet available; do not create estimates merely to complete the form.</p><PrintButton label="Print or save as PDF"/><p className="intake-privacy">This page does not upload or store anything you enter. When complete, print it or use your browser to save it as a PDF.</p></div></section>
  <section className="intake-path" aria-label="Three-step site review process"><article><span>01</span><div><h2>Complete</h2><p>Use available records and mark unknown information “To be confirmed”.</p></div></article><article><span>02</span><div><h2>Save</h2><p>Print a paper copy or save a PDF through your browser.</p></div></article><article><span>03</span><div><h2>Confirm delivery</h2><p>Call GTC to agree a secure delivery method for formal and sensitive documents.</p></div></article></section>
  <nav className="intake-index" aria-label="Worksheet sections"><a href="#intake-contact">Basic details</a><a href="#intake-waste">Waste scale</a><a href="#intake-site">Site conditions</a><a href="#intake-goals">Objectives</a><a href="#intake-documents">Documents</a><a href="#intake-questions">Questions</a></nav>
  <form className="intake-form">
    <section className="intake-section" id="intake-contact"><header><b>01</b><div><h2>Contact and project details</h2><p>Identify the responsible organisation and proposed location.</p></div></header><div className="intake-fields"><Field label="Country / region"/><Field label="City / administrative area"/><Field label="Government or organisation"/><Field label="Responsible department"/><Field label="Contact name and title"/><Field label="Telephone or email"/><Field label="Site name" wide/><Field label="Site address or coordinates" wide/></div></section>
    <section className="intake-section" id="intake-waste"><header><b>02</b><div><h2>Waste source and scale</h2><p>Separate legacy stock from current daily additions.</p></div></header><div className="intake-fields"><Field label="Estimated total stock (tonnes)"/><Field label="Current daily additions (tonnes/day)"/><Field label="Earliest disposal year"/><Field label="Sample quantity available"/><Field label="Date of existing sampling or composition analysis" wide/></div><div className="intake-options"><p>Primary sources</p><div><Check>Legacy landfill waste</Check><Check>Municipal solid waste</Check><Check>Oversize fraction after transfer or sorting</Check><Check>Mixed waste plastics</Check><Check>Other</Check></div></div><label className="intake-textarea"><span>Known composition, moisture, contaminants or other characteristics</span><textarea rows={4}/></label></section>
    <section className="intake-section" id="intake-site"><header><b>03</b><div><h2>Site and infrastructure</h2><p>Equipment planning requires land, access and energy information.</p></div></header><div className="intake-fields"><Field label="Available land area"/><Field label="Existing building or covered area"/><Field label="Available electricity / capacity"/><Field label="Water supply and drainage"/><Field label="Road and heavy-vehicle access" wide/></div><div className="intake-options"><p>Current site status</p><div><Check>Still receiving waste</Check><Check>Closed landfill</Check><Check>Phased construction possible</Check><Check>Near homes or sensitive receptors</Check><Check>Status to be confirmed</Check></div></div></section>
    <section className="intake-section" id="intake-goals"><header><b>04</b><div><h2>Current treatment and governance objectives</h2><p>Describe the current cost and the problems to address first.</p></div></header><label className="intake-textarea"><span>Current treatment, transfer, incineration or landfilling approach</span><textarea rows={4}/></label><div className="intake-options"><p>Priority objectives</p><div><Check>Reduce landfilling</Check><Check>Reduce odour or environmental risk</Check><Check>Recover mixed plastics</Check><Check>Restore land use</Check><Check>Establish destinations for recycled material</Check><Check>Other</Check></div></div><div className="intake-fields"><Field label="Preferred assessment start"/><Field label="Target completion or policy year"/></div></section>
    <section className="intake-section" id="intake-documents"><header><b>05</b><div><h2>Regulation, monitoring and existing documents</h2><p>A formal pathway must reflect local law and environmental conditions.</p></div></header><div className="intake-options intake-documents"><p>Available information</p><div><Check>Site plan or aerial image</Check><Check>Site photographs and films</Check><Check>Waste composition or sampling report</Check><Check>Historical intake records</Check><Check>Groundwater or leachate monitoring</Check><Check>Air, odour or dust monitoring</Check><Check>Environmental assessment</Check><Check>Permits and land information</Check><Check>Current treatment-cost data</Check><Check>Other technical reports</Check></div></div><label className="intake-textarea"><span>Local regulation, procurement procedure or other constraints</span><textarea rows={4}/></label></section>
    <section className="intake-section intake-final" id="intake-questions"><header><b>06</b><div><h2>Questions for the first technical meeting</h2><p>List the three to five questions GTC most needs to address.</p></div></header><label className="intake-textarea"><span>Questions and additional context</span><textarea rows={8}/></label><aside><h3>Before sharing</h3><Check>Data includes units and source years</Check><Check>Estimates and formal records are clearly distinguished</Check><Check>A transfer method has been agreed for sensitive or restricted documents</Check><Check>Unknown fields are marked “To be confirmed”</Check></aside></section>
  </form>
  <section className="intake-end"><div><p className="eyebrow">NEXT STEP</p><h2>After organising the information<br/>arrange an initial technical discussion</h2></div><div><p>This page does not submit data automatically. Print or save the worksheet as a PDF, then call GTC to confirm how formal documents and site information should be transferred.</p><div className="intake-end-actions"><PrintButton label="Print or save as PDF"/><a className="button primary" href="tel:+88665811589">Call +886 6 581 1589</a></div></div></section>
  <footer className="mini-footer governance-footer"><Link href="/en">Home</Link><Link href="/en/governance">Governance partnership</Link><Link href="/en/reports">Test reports</Link><span>GTC Global Holding Group</span></footer>
</main>}
