import type { Metadata } from "next";
import Link from "next/link";
import { reports } from "../../reports/data";
import SiteHeader from "../../../components/SiteHeader";
import { createPageMetadata } from "../../../lib/site";

export const metadata: Metadata = createPageMetadata({title:"Waste Governance Cases & Evidence | GTC",description:"Review GTC field films, project statements from corporate materials, product test documents and the evidence still required for public-sector due diligence.",path:"/en/governance/evidence",alternatePath:"/governance/evidence",locale:"en_US"});

const observedStages = [
  {number:"01",time:"Approx. 00:24",title:"Site and operating environment",description:"Waste storage areas, work vehicles and operating facilities are visible, showing the scale of the field setting. The public material does not identify the filming location or date."},
  {number:"02",time:"Approx. 02:14",title:"Front-end sorting process",description:"Conveying and sorting equipment can be seen processing mixed material. This shows that the process exists, but cannot establish equipment throughput or recovery rate."},
  {number:"03",time:"Approx. 04:03",title:"Downstream material production",description:"The film records a production setting for sorted material, providing visual evidence of a resource destination. A complete material balance still requires project data."},
];

const evidenceRegister = [
  {type:"Field film",state:"Published",supports:"Observation of excavation, conveying, sorting and downstream manufacturing settings.",boundary:"Does not disclose the site, filming date, continuous-run duration or equipment throughput."},
  {type:"Changshankou project statement",state:"Stated in corporate materials",supports:"Company materials state that the project passed a national-level expert review in 2021.",boundary:"The original review, reviewing body, scope and quantitative results are not published on this site."},
  {type:"Material and product tests",state:"Published",supports:"Results for specific samples under the conditions recorded in each material, weathering or product report.",boundary:"Product testing alone cannot establish waste-governance capacity, pollution control or overall recovery rate."},
  {type:"Product and processing films",state:"Published",supports:"Observation of Siwood machining, pallet production and material application directions.",boundary:"The footage does not establish that all feedstock came from the same governance site."},
];

const featuredReports = reports.filter((report)=>["wpc-material-test","pallet-inspection","formwork-test"].includes(report.slug));

export default function GovernanceEvidencePage(){return <main className="gov-evidence-page">
  <SiteHeader locale="en" />
  <section className="gov-evidence-hero"><div><p className="eyebrow">CASE RECORD / EVIDENCE REVIEW</p><h1>Waste governance<br/>cases and evidence</h1></div><div className="gov-evidence-hero-copy"><p>Place field records, company statements and test documents in their proper roles—so partners can see what is available now and what is still required before a formal decision.</p><div className="gov-evidence-hero-links"><a href="#field-record">View field record <span>↓</span></a><Link href="/en/governance/intake">Start site review <span>↗</span></Link></div></div></section>

  <section className="gov-evidence-position"><header><p className="eyebrow">EVIDENCE POSITION / 01</p><h2>First define<br/>what the evidence supports</h2></header><div className="gov-evidence-status"><article><span>Published</span><h3>Available for direct review</h3><p>The governance film, material-processing films, product catalog and ten material or product test documents.</p></article><article><span>Stated in company materials</span><h3>Statement requiring its source document</h3><p>The Changshankou pilot project passed a national-level expert review in 2021; the original review is not yet published here.</p></article><article><span>Required for a formal project</span><h3>No conclusion yet</h3><p>Throughput, recovery rate, material balance, emissions, continuous operation, capital cost and operating cost.</p></article></div></section>

  <section className="gov-field-record" id="field-record"><header className="gov-evidence-section-heading"><p className="eyebrow">FIELD RECORD / 02</p><h2>Watch the original film<br/>before reading observations</h2><p>The original film supplied by GTC is presented directly below. Observations are limited to visible content and do not infer undisclosed engineering data from footage.</p></header><div className="gov-evidence-video"><video controls playsInline preload="metadata" aria-label="Landfill excavation, remediation and production process"><source src="/videos/landfill-recovery.mp4" type="video/mp4"/>Your browser does not support video playback. <a href="/videos/landfill-recovery.mp4">Open the video</a>.</video><div><p className="eyebrow">FULL FIELD FILM</p><h3>Landfill Excavation, Remediation and Production Process</h3><p>The original film supplied by GTC runs for approximately five minutes. It supports preliminary process understanding; formal verification also requires site documents, equipment specifications and operating records.</p><Link href="/en/videos#landfill-recovery">Open the film archive for context <span>↗</span></Link></div></div><div className="gov-observed-label"><p className="eyebrow">OBSERVED IN THE FILM</p><p>Times are approximate navigation aids. Refer to the player display.</p></div><div className="gov-observed-stages">{observedStages.map((stage)=><article key={stage.number}><span>{stage.number}</span><div><small>{stage.time}</small><h3>{stage.title}</h3><p>{stage.description}</p></div></article>)}</div></section>

  <section className="gov-project-record" id="project-record"><div className="gov-project-year"><span>2021</span><p>Project milestone stated in the corporate presentation</p></div><div className="gov-project-copy"><p className="eyebrow">CORPORATE RECORD / 03</p><h2>Changshankou pilot project</h2><blockquote>Company materials state that the Changshankou pilot project passed a national-level expert review in 2021.</blockquote><div className="gov-claim-boundaries"><article><h3>What can currently be stated</h3><p>This is an existing project record in GTC&apos;s corporate presentation and may describe the company&apos;s claimed development and review milestone.</p></article><article><h3>What cannot yet be inferred</h3><p>Until the source review is published, its scope, capacity, environmental performance, economics and long-term operating results cannot be independently extended.</p></article></div><p className="gov-source-note">Source: GTC corporate profile presentation. The original review or a publishable summary remains to be added.</p></div></section>

  <section className="gov-evidence-register" id="evidence-register"><header className="gov-evidence-section-heading"><p className="eyebrow">EVIDENCE REGISTER / 04</p><h2>Scope of evidence</h2><p>Each item retains its use and boundary so product tests, footage and city-scale governance performance are not treated as interchangeable.</p></header><div className="gov-register-table" role="table" aria-label="Scope of waste-governance evidence"><div className="gov-register-head" role="row"><span role="columnheader">Evidence type</span><span role="columnheader">Current status</span><span role="columnheader">Can support</span><span role="columnheader">Cannot replace</span></div>{evidenceRegister.map((item,index)=><article role="row" key={item.type}><h3 role="cell"><b>{String(index+1).padStart(2,"0")}</b>{item.type}</h3><p role="cell"><span>Current status</span>{item.state}</p><p role="cell"><span>Can support</span>{item.supports}</p><p role="cell"><span>Cannot replace</span>{item.boundary}</p></article>)}</div></section>

  <section className="gov-product-proof"><header><p className="eyebrow">DOWNSTREAM VERIFICATION / 05</p><h2>Product tests apply to<br/>specific recovered-material samples</h2><p>These documents show material or product performance under the conditions of each report. They support understanding of downstream use, but are not reports of waste-governance performance.</p></header><div className="gov-report-links">{featuredReports.map((report,index)=><a href={report.file} target="_blank" rel="noreferrer" key={report.slug}><span>{String(index+1).padStart(2,"0")}</span><div><small>{report.agency} / {report.category}</small><h3>{report.title}</h3></div><b>Open original document ↗</b></a>)}</div><Link className="text-link" href="/en/reports">View all ten test documents <span>↗</span></Link></section>

  <section className="gov-next-review" id="next-review"><div><p className="eyebrow">NEXT DUE DILIGENCE / 06</p><h2>Turn remaining gaps<br/>into a verification list</h2></div><div><p>The next stage should obtain the original review document, basic site data, waste composition, equipment specifications, material balance, environmental monitoring, continuous-operation records and cost boundaries. These determine whether the technology fits a particular city; website copy cannot substitute for them.</p><div className="gov-next-actions"><Link className="button primary" href="/en/governance/intake">Complete site-review worksheet</Link><Link className="button outline" href="/en/governance">Back to partnership framework</Link></div></div></section>

  <footer className="mini-footer governance-footer"><Link href="/en">Home</Link><Link href="/en/governance">Governance partnership</Link><Link href="/en/videos">Field films</Link><Link href="/en/reports">Test reports</Link><span>GTC Global Holding Group</span></footer>
</main>}
