import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../../components/SiteHeader";
import { createPageMetadata } from "../../lib/site";

export const metadata: Metadata = createPageMetadata({title:"Municipal Waste Governance Partnership | GTC",description:"A public-sector partnership framework covering landfill excavation, mixed-plastic sorting, material recovery and the information required for an initial site review.",path:"/en/governance",alternatePath:"/governance",locale:"en_US"});

const process = [
  {number:"01",title:"Site and waste inventory",description:"Confirm waste sources, years in place, estimated volume, current treatment and site conditions. Where records are incomplete, sampling and a site survey provide the missing basis for assessment."},
  {number:"02",title:"Excavation and front-end sorting",description:"Plan excavation and sorting around site conditions, separating recoverables, inert material and lightweight oversize fractions. Equipment must be configured against the actual waste composition."},
  {number:"03",title:"Precision sorting of mixed plastics",description:"Use automated sorting to address mixed waste plastics and lightweight fractions that conventional recycling chains struggle to use, creating more stable feed conditions for material recovery."},
  {number:"04",title:"Composite-material manufacturing",description:"Company materials state that the core material process does not rely on incineration or water washing, and turns sorted feedstock into a composite polymer material for further processing."},
  {number:"05",title:"Product applications and recovery pathway",description:"Recovered material can extend into Siwood building products, landscape components and pallets. Collection and remanufacturing after use depend on the material and project specification."},
];

const collaboration = [
  ["01","Submit a site summary","Provide the city, waste source, estimated stock, current photographs and the most urgent problem to address."],
  ["02","Confirm the technical scope","Confirm the treatable scope, sampling information still required, and local regulatory and infrastructure conditions."],
  ["03","Plan sampling or trials","Use waste composition to decide whether sample tests, a small-scale validation or an on-site survey are required."],
  ["04","Assess the project pathway","Once essential data is available, assess process configuration, output destinations, installation conditions and the partnership scope."],
];

const dueDiligence = [
  ["Treatment capacity","Daily throughput, annual operating days and expansion approach"],
  ["Material balance","Feedstock, recoverables, recycled material and final residual fractions"],
  ["Environmental controls","Air emissions, wastewater, dust, odour, noise, soil and groundwater monitoring"],
  ["Installation conditions","Land, energy, labour, equipment layout, construction period and maintenance"],
  ["Commercial conditions","Capital and operating cost, material and product destinations, and partnership model"],
  ["Regulatory documents","Local permits, environmental review, engineering standards and third-party verification"],
];

export default function GovernancePage(){return <main className="governance-page">
  <SiteHeader locale="en" />
  <section className="governance-hero"><div className="governance-hero-copy"><p className="eyebrow">PUBLIC SECTOR PARTNERSHIP / WASTE REMEDIATION</p><h1>Municipal waste governance partnership</h1><p>For legacy landfills and mixed waste plastics that cannot readily enter existing recycling systems, GTC places excavation, precision sorting and material remanufacturing within one pathway.</p><div className="governance-hero-actions"><Link className="button primary" href="/en/governance/intake">Start a site review</Link><a className="text-link" href="#cooperation">How partnership begins <span>↓</span></a><Link className="text-link" href="/en/governance/evidence">Review available evidence <span>↗</span></Link></div></div><div className="governance-hero-index" aria-label="Program summary"><span>01</span><p>LANDFILL<br/>TO RESOURCE</p><dl><div><dt>Target</dt><dd>Landfilled waste and mixed plastics</dd></div><div><dt>Method</dt><dd>Excavation, sorting and material recovery</dd></div><div><dt>Purpose</dt><dd>Reduce disposal and establish resource destinations</dd></div></dl></div></section>

  <section className="governance-scope" id="scope"><div className="governance-heading"><p className="eyebrow">SCOPE / 01</p><h2>Define the problem<br/>before selecting the pathway</h2></div><div className="scope-summary"><p className="scope-lead">Waste governance cannot be answered by one machine. Composition, moisture, age and regulatory conditions vary by site, so work should begin with records and sample validation.</p><dl><div><dt>Current focus</dt><dd>Legacy landfills, lightweight oversize fractions and mixed plastics that conventional recycling struggles to use.</dd></div><div><dt>Technical purpose</dt><dd>Separate usable fractions and turn mixed plastics into material that can be manufactured again.</dd></div><div><dt>Project basis</dt><dd>Throughput, recovery rate, residuals and equipment scale must be assessed against actual samples and site data.</dd></div></dl></div></section>

  <section className="governance-process" id="process"><header><p className="eyebrow">PROCESS / 02</p><h2>From site inventory to material destination</h2><p>This is the governance logic supported by the currently available material. Engineering flow must be adjusted for waste composition, local regulation and project goals.</p></header><ol>{process.map((step)=><li key={step.number}><b>{step.number}</b><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol></section>

  <section className="governance-evidence" id="evidence"><div className="evidence-film"><video controls playsInline preload="metadata" aria-label="Landfill excavation, remediation and production process"><source src="/videos/landfill-recovery.mp4" type="video/mp4"/>Your browser does not support video playback. <a href="/videos/landfill-recovery.mp4">Open the video</a>.</video><p>Original film supplied by GTC / Landfill excavation, remediation and production process</p></div><div className="evidence-copy"><p className="eyebrow">FIELD EVIDENCE / 03</p><h2>Field records and existing verification</h2><p>Company materials state that the Changshankou pilot project passed a national-level expert review in 2021. The site also publishes a landfill-governance film, material-processing records and product test documents for preliminary review.</p><p className="evidence-note">The project statement above is adapted from GTC&apos;s corporate presentation. Formal assessment still requires the original review document, project boundaries, operating data and continuous-run records.</p><div className="evidence-links"><Link href="/en/governance/evidence">Open the cases and evidence page <span>↗</span></Link><Link href="/en/videos#landfill-recovery">View all field films <span>↗</span></Link><Link href="/en/reports">View product test documents <span>↗</span></Link></div></div></section>

  <section className="governance-proof"><header><p className="eyebrow">DUE DILIGENCE / 04</p><h2>Information required for project assessment</h2><p>Current reports mainly address recycled materials and product performance. Government procurement and city-scale projects also require the site and engineering evidence below; product tests cannot substitute for governance-performance verification.</p></header><div className="proof-action"><Link className="button outline" href="/en/governance/intake">Open the site-review worksheet</Link><span>Complete it in the browser, then print or save as PDF.</span></div><div className="due-diligence-list">{dueDiligence.map(([title,description],index)=><div key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{description}</p></div>)}</div></section>

  <section className="governance-output"><div><p className="eyebrow">RESOURCE OUTPUT / 05</p><h2>Recovered material<br/>needs a defined destination</h2><p>Siwood building materials, landscape components and circular pallets show possible downstream applications. Every engineering use must still be selected against specifications, reports and local standards.</p><Link className="button outline" href="/en/products">View materials and products</Link></div><div className="output-images"><Link href="/en/products/architecture"><img src="/catalog/architecture.jpg" alt="Siwood architecture and landscape applications" loading="lazy"/><span>Architecture and landscape applications</span></Link><Link href="/en/products/recycled-pallet"><img src="/catalog/pallet.jpg" alt="Recycled-plastic pallet" loading="lazy"/><span>Circular pallets</span></Link></div></section>

  <section className="governance-cooperation" id="cooperation"><header><p className="eyebrow">PROJECT INTAKE / 06</p><h2>Public-sector partnership process</h2><p>A first enquiry does not require a complete specification. Begin with the available site information, then identify the sampling, documents and technical discussion still required.</p></header><div className="collaboration-list">{collaboration.map(([number,title,description])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{description}</p></article>)}</div></section>

  <section className="governance-contact" id="contact"><div><p className="eyebrow">START A SITE REVIEW</p><h2>Begin technical assessment<br/>with one site</h2></div><div><p>Use the worksheet to organise the information already available. Then contact GTC to confirm a secure delivery method for formal or sensitive project documents.</p><div className="governance-contact-actions"><Link className="button outline" href="/en/governance/intake">Complete site-review form</Link><a className="button primary" href="tel:+88665811589">Call +886 6 581 1589</a></div><p className="contact-limitation">An initial review does not constitute a performance guarantee, engineering design or commercial quotation.</p></div></section>

  <footer className="mini-footer governance-footer"><Link href="/en">Home</Link><Link href="/en/governance/evidence">Cases & evidence</Link><Link href="/en/products">Products</Link><Link href="/en/reports">Test reports</Link><span>GTC Global Holding Group</span></footer>
</main>}
